In [37]:
import numpy as np
from pprint import pprint

In [56]:
def sum_nums(a:int, b:int) -> int:
    return a+b
sum_nums(a = 1,b = 2) # (1)
sum_nums(1, 2) # (2)

3

In [69]:
a = np.array([1,2,3]) # a1, a2, a3
pprint(a)
pprint(a.shape)
print(f'a1: {a[1]}') 
a = a.reshape(3,1) # czasem nie musisz przypuisywac a czasem musisz
pprint(a)
pprint(a.shape)
print(f'a1: {a[1]}') 


array([1, 2, 3])
(3,)
a1: 2
array([[1],
       [2],
       [3]])
(3, 1)
a1: [2]


In [80]:
import numpy as np
from pprint import pprint,3], [4,5,6]]) # 
pprint(b)
b = b.reshape(-1) # flatten
pprint(b)

array([[1, 2, 3],
       [4, 5, 6]])
array([1, 2, 3, 4, 5, 6])
<class 'numpy.ndarray'>


In [53]:

def onesToArray(X: np.ndarray, d: str) -> np.ndarray:
    """
    X - orginal array
    d - dimension of the array
    """
    rows = X.shape[0]
    cols = X.shape[1]
    if d == 'r':
        Xprim = np.hstack((X, np.ones(shape=(rows,1))))
    elif d == 'l':
        Xprim = np.hstack((np.ones((rows,1)), X))
    elif d == 'd':    
        Xprim = np.vstack((X, np.ones((1,cols))))
    elif d == 'u': 
        Xprim = np.vstack((np.ones((1,cols)), X))
    else:
        print("Wrong dimension type u, d, r, l")
    return Xprim
        
# np.array([[1,2,3],[4,5,6]]).shape[0]
X_input = np.array([[1,2,3],[4,5,6]])
anwser = onesToArray(X = X_input, d='u')
anwser = onesToArray(anwser, 'r')
anwser = onesToArray(anwser, 'l')
anwser


array([[1., 1., 1., 1., 1.],
       [1., 1., 2., 3., 1.],
       [1., 4., 5., 6., 1.]])

 - `hstack` - Stack arrays in sequence horizontally 
 - `vstack` - Stack arrays in sequence vertically
```python
a = np.array((1,2,3)) # macierz orginalna
b = np.array((4,5,6)) # macierz z jedynkami
np.hstack((a,b))
>>> array([1, 2, 3, 4, 5, 6])
```
a + b # z prawej
b + a # z lewej

